/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 08 18:52:42 GMT 2017
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.Node;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Node_ESTest extends Node_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Node<Object> node0 = new Node<Object>((Object) "C@}05DJes4wuT");
      Node<Object> node1 = new Node<Object>((Object) null);
      node1.setNext(node0);
      assertNotSame(node1, node0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Node<Object> node0 = new Node<Object>((Object) null);
      Object object0 = node0.getObject();
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Node<Object> node0 = new Node<Object>((Object) "C@}05DJes4wuT");
      node0.setNext(node0);
      Node<Object> node1 = node0.getNext();
      assertSame(node0, node1);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Node<Object> node0 = new Node<Object>((Object) "C@}05DJes4wuT");
      String string0 = (String)node0.getObject();
      assertEquals("C@}05DJes4wuT", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Node<Object> node0 = new Node<Object>((Object) "C@}05DJes4wuT");
      Node<Object> node1 = node0.getNext();
      assertNull(node1);
  }
}
